[build]
  base = "apps/form-app"
  command = "npm install --include=dev && npm run build"
  publish = ".next"

# Functions handled by Next.js App Router
# [functions]
#   directory = "netlify/functions"
#   node_bundler = "nft"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# API routes are handled by Next.js App Router automatically
# No redirects needed for /api/* - Next.js will handle these

# Catch-all redirect for SPA fallback (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://wareworks-backend.netlify.app"

# Environment variables for deploy preview
[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://wareworks-backend.netlify.app"