[build]
  base = "apps/form-app"
  command = "npm install --include=dev && npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "nft"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Clean API route redirect for V2 functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/v2/:splat"
  status = 200

# Optional: direct alias for submit-application
[[redirects]]
  from = "/api/submit-application"
  to = "/.netlify/functions/v2/submit-application"
  status = 200

# Catch-all redirect for SPA fallback (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://wareworks-backend.netlify.app"

# Environment variables for deploy preview
[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://wareworks-backend.netlify.app"