[build]
  base = "apps/form-app"
  command = "npm run build"
  publish = "apps/form-app/.next"

[functions]
  directory = "netlify/functions"
  node_bundler = "nft"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Modern API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/v2/:splat"
  status = 200

# Legacy compatibility
[[redirects]]
  from = "/.netlify/functions/submit-application"
  to = "/.netlify/functions/legacy/submit-application"
  status = 200

# Form app routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://wareworks-backend.netlify.app"

[context.deploy-preview.environment]
  NODE_ENV = "development"